services:
  mongo:
    image: mongo:latest
    container_name: sharebox-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sharebox
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express:latest
    container_name: sharebox-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/sharebox?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo-data: